services:
  - type: web
    name: vayusense
    runtime: docker
    dockerfilePath: ./deploy/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: GOOGLE_GENAI_USE_VERTEXAI
        value: "FALSE"
      - key: MODEL
        value: gemini-2.5-flash
      - key: GOOGLE_API_KEY
        sync: false
